apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
spec:
  storageClassName: my-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-nfs
provisioner: deployment.apps/nfs-subdir-external-provisioner
parameters:
  server: "192.168.88.25"
  path: "/var/nfs_share"
  readOnly: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        command: ['sh', '-c', 'sleep infinity']
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/shared"
          name: multitool-vol
      volumes:
      - name: multitool-vol
        nfs:
          server: "192.168.88.25"
          path: "/var/nfs_share"
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
spec:
  selector:
    app: multitool
  ports:
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
---
